CREATE TABLE API_CREDENTIALS (
    credential_id SERIAL PRIMARY KEY
    , user_id INT NOT NULL
    , hash_api VARCHAR(255) NOT NULL
    , hash_secret VARCHAR(255) NOT NULL
    , api_name VARCHAR(255) NOT NULL
    , exp_date TIMESTAMP WITH TIME ZONE
	, flg_active BOOLEAN DEFAULT TRUE
    , FOREIGN KEY (user_id) REFERENCES USERS(user_id)
	, ins_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , ins_user INT
    , upt_date TIMESTAMP WITH TIME ZONE
    , upt_user INT
);

--OUR FOREIGN KEY IS WITH THE USERS TABLE
SELECT * FROM API_CREDENTIALS

/*
DROP TABLE API_CREDENTIALS
*/